apiVersion: batch/v1
kind: Job
metadata:
  labels:
    release: jenkins-x
  name: jx-boot
spec:
  backoffLimit: 5
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        release: jenkins-x
    spec:
      containers:
      - args:
        - boot
        - run
        - -b
        - --git-url
        - {{ .Values.jxRequirements.bootConfigURL | quote }}
        - --git-ref
        - {{ .Values.jxRequirements.bootConfigRef | quote }}
        - --versions-repo
        - {{ .Values.jxRequirements.versionStream.url | quote }}
        - --versions-ref
        - {{ .Values.jxRequirements.versionStream.ref | quote }}
        command:
        - jxl

        env:
        - name: GIT_COMMITTER_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_NAME
          value: jenkins-x-bot
        - name: GIT_COMMITTER_NAME
          value: jenkins-x-bot
        - name: JX_BATCH_MODE
          value: "true"
        - name: JX_LOG_FORMAT
          value: "json"

        - name: JX_HELM3
          value: "true"
        - name: JX_HELMFILE
          value: "true"
        - name: JX_SECRETS_YAML
          value: /secrets/jx-boot/secrets.yaml
        - name: JX_INTERPRET_PIPELINE
          value: "true"
        - name: JX_HOME
          value: /secrets
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: boot
      restartPolicy: Never
      serviceAccountName: {{ include "jxl-boot.serviceAccountName" . }}
